site_name: MLtraq
site_description: Track and Collaborate on AI Experiments.
site_url: https://mltraq.com
docs_dir: mkdocs/
site_dir: dist/docs
theme: # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  features:
    - navigation.tracking
    # - navigation.expand
    #- navigation.top
    #- toc.integrate
    #- navigation.path
    #- navigation.sections
    - content.code.copy
    - search.highlight

  logo: assets/img/favicon-white.svg
  favicon: assets/img/favicon-black.svg
  name: material
  palette:
  - scheme: default
    primary: black
    accent: deep orange
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: black
    accent: deep orange
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
repo_name: elehcimd/mltraq
repo_url: https://github.com/elehcimd/mltraq
edit_uri: ""


# List of markdown extensions available by default:
# https://python-markdown.github.io/extensions/
markdown_extensions:
- toc:
    permalink: "#" # Create permalinks for headers inside each page
- admonition # Render call-outs like WARNING: , ... https://squidfunk.github.io/mkdocs-material/reference/admonitions/
- mdx_include # Let .md files include lines from .py files
- extra # The "extra" extension, handling tables, footnotes, definitions, ...: https://python-markdown.github.io/extensions/extra/
- pymdownx.details
- pymdownx.superfences: # Adding support for Mermaid.js diagrams: https://squidfunk.github.io/mkdocs-material/reference/diagrams/#usage
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
    - name: vegalite
      class: vegalite
      format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight: # Code highlighting inside code blocks
    # linenums: true
    line_anchors: "code-anchor"
    anchor_linenums: true
- pymdownx.inlinehilite # Inline code highlighting
- pymdownx.snippets # Include external files as code blocks
# Documentation on code blocks: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
- pymdownx.tasklist:
    custom_checkbox: true
      
nav:
  - index.md
  - Tutorial:
    - tutorial/index.md
    - tutorial/01-sessions.md
    - tutorial/02-experiments.md
    - tutorial/03-parameters.md
    - tutorial/04-storage.md
    - tutorial/05-ml.md
  - How-to guides:
    - howto/01-tracking.md
    - howto/02-artifacts-storage.md
  - Advanced topics:
    - advanced/computation-model.md
    - advanced/state.md
    - advanced/storage.md
    - advanced/options.md
    - advanced/datastore.md
  # - Blog: blog/index.md
  - Benchmarks:
    - benchmarks/speed.md
  - FAQ:
    - faq.md    
  - Become a sponsor: sponsor.md
  - License: license.md
  - Citing: cite.md
  
plugins:
    - search # If you are creating the plugins entry in your config file, you should also insert a line for the search plugin.
    - macros:
        module_name: mkdocs/mymacros
        #on_error_fail: true
    - mkdocstrings
    - charts # mkdocs-charts-plugin
    #- blog:
    #    pagination_per_page: 1

extra_css:
- assets/css/custom.css

extra_javascript:
  - assets/js/custom.js
  - https://cdn.jsdelivr.net/npm/vega@5 # mkdocs-charts-plugin
  - https://cdn.jsdelivr.net/npm/vega-lite@5 # mkdocs-charts-plugin
  - https://cdn.jsdelivr.net/npm/vega-embed@6 # mkdocs-charts-plugin

copyright: Copyright © 2022 - 2024 Michele Dallachiesa


extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/elehcimd/mltraq
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/dallachiesa/
